package HotelBooking.actions;

/*Generated by MPS */

import jetbrains.mps.openapi.actions.descriptor.NodeFactory;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.model.SModel;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import HotelBooking.behavior.Hotel__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.action.SNodeFactoryOperations;

public class incrementRoomNumber {
  public static class NodeFactory_9200123026167588573 implements NodeFactory {
    public void setup(SNode newNode, SNode sampleNode, SNode enclosingNode, SModel model) {
      SPropertyOperations.assign(newNode, MetaAdapterFactory.getProperty(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x2d11723256bb3a6bL, 0x2d11723256bb3a78L, "roomNumber"), (int) Hotel__BehaviorDescriptor.GetTotalRooms_id2Ohsz9mIXfU.invoke(SNodeOperations.cast(enclosingNode, MetaAdapterFactory.getConcept(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x2d11723256bb12aeL, "HotelBooking.structure.Hotel"))));
      SPropertyOperations.assign(SNodeFactoryOperations.addNewChild(newNode, MetaAdapterFactory.getContainmentLink(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x2d11723256bb3a6bL, 0x7fad6725e0988025L, "Facilities"), MetaAdapterFactory.getConcept(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x7fad6725e0988022L, "HotelBooking.structure.Facility")), MetaAdapterFactory.getProperty(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x7fad6725e0988022L, 0x26ee893bae652778L, "type"), "Bathroom");
      if (SNodeOperations.isInstanceOf(newNode, MetaAdapterFactory.getConcept(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x6c41d16d1d9adfe2L, "HotelBooking.structure.Studio"))) {
        SPropertyOperations.assign(SNodeFactoryOperations.addNewChild(newNode, MetaAdapterFactory.getContainmentLink(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x2d11723256bb3a6bL, 0x7fad6725e0988025L, "Facilities"), MetaAdapterFactory.getConcept(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x7fad6725e0988022L, "HotelBooking.structure.Facility")), MetaAdapterFactory.getProperty(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x7fad6725e0988022L, 0x26ee893bae652778L, "type"), "LivingArea");
        SPropertyOperations.assign(SNodeFactoryOperations.addNewChild(newNode, MetaAdapterFactory.getContainmentLink(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x2d11723256bb3a6bL, 0x7fad6725e0988025L, "Facilities"), MetaAdapterFactory.getConcept(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x7fad6725e0988022L, "HotelBooking.structure.Facility")), MetaAdapterFactory.getProperty(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x7fad6725e0988022L, 0x26ee893bae652778L, "type"), "Kitchen");
      }
      if (SNodeOperations.isInstanceOf(newNode, MetaAdapterFactory.getConcept(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x7fad6725e0987fdeL, "HotelBooking.structure.Suite"))) {
        SPropertyOperations.assign(SNodeFactoryOperations.addNewChild(newNode, MetaAdapterFactory.getContainmentLink(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x2d11723256bb3a6bL, 0x7fad6725e0988025L, "Facilities"), MetaAdapterFactory.getConcept(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x7fad6725e0988022L, "HotelBooking.structure.Facility")), MetaAdapterFactory.getProperty(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x7fad6725e0988022L, 0x26ee893bae652778L, "type"), "Bathroom");
        SPropertyOperations.assign(SNodeFactoryOperations.addNewChild(newNode, MetaAdapterFactory.getContainmentLink(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x2d11723256bb3a6bL, 0x7fad6725e0988025L, "Facilities"), MetaAdapterFactory.getConcept(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x7fad6725e0988022L, "HotelBooking.structure.Facility")), MetaAdapterFactory.getProperty(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x7fad6725e0988022L, 0x26ee893bae652778L, "type"), "futon");
        SPropertyOperations.assign(SNodeFactoryOperations.addNewChild(newNode, MetaAdapterFactory.getContainmentLink(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x2d11723256bb3a6bL, 0x7fad6725e0988025L, "Facilities"), MetaAdapterFactory.getConcept(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x7fad6725e0988022L, "HotelBooking.structure.Facility")), MetaAdapterFactory.getProperty(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x7fad6725e0988022L, 0x26ee893bae652778L, "type"), "LivingArea");
        SPropertyOperations.assign(SNodeFactoryOperations.addNewChild(newNode, MetaAdapterFactory.getContainmentLink(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x2d11723256bb3a6bL, 0x7fad6725e0988025L, "Facilities"), MetaAdapterFactory.getConcept(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x7fad6725e0988022L, "HotelBooking.structure.Facility")), MetaAdapterFactory.getProperty(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x7fad6725e0988022L, 0x26ee893bae652778L, "type"), "Kitchen");
      }
    }
  }
}
