package HotelBooking.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import java.util.Arrays;

public class EnumerationDescriptor_FacillityName extends EnumerationDescriptorBase {

  public EnumerationDescriptor_FacillityName() {
    super(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x7fad6725e0a3467dL, "FacillityName", "r:c1ca0d93-0221-4e5d-94f3-6bf04aa3666a(HotelBooking.structure)/9200123026168039037", PrimitiveTypeId.STRING);
  }

  private final EnumerationDescriptor.MemberDescriptor VALUE_Bathroom_0 = new EnumerationDescriptor.MemberDescriptor("Bathroom", "Bathroom", "r:c1ca0d93-0221-4e5d-94f3-6bf04aa3666a(HotelBooking.structure)/9200123026168039038", "Bathroom");
  private final EnumerationDescriptor.MemberDescriptor VALUE_Kitchen_0 = new EnumerationDescriptor.MemberDescriptor("Kitchen", "Kitchen", "r:c1ca0d93-0221-4e5d-94f3-6bf04aa3666a(HotelBooking.structure)/9200123026168039039", "Kitchen");
  private final EnumerationDescriptor.MemberDescriptor VALUE_LivingArea_0 = new EnumerationDescriptor.MemberDescriptor("LivingArea", "LivingArea", "r:c1ca0d93-0221-4e5d-94f3-6bf04aa3666a(HotelBooking.structure)/9200123026168039042", "LivingArea");
  private final EnumerationDescriptor.MemberDescriptor VALUE_futon_0 = new EnumerationDescriptor.MemberDescriptor("futon", "Futon", "r:c1ca0d93-0221-4e5d-94f3-6bf04aa3666a(HotelBooking.structure)/7800746296160878316", "Futon");

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return VALUE_Bathroom_0;
  }

  @NotNull
  @Override
  public Collection<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return Arrays.asList(VALUE_Bathroom_0, VALUE_Kitchen_0, VALUE_LivingArea_0, VALUE_futon_0);
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String string) {
    if (string == null) {
      return null;
    }
    switch (string) {
      case "Bathroom":
        return VALUE_Bathroom_0;
      case "Kitchen":
        return VALUE_Kitchen_0;
      case "LivingArea":
        return VALUE_LivingArea_0;
      case "futon":
        return VALUE_futon_0;
    }
    return null;
  }
}
