package HotelBooking.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import java.util.Arrays;

public class EnumerationDescriptor_BedType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_BedType() {
    super(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x26ee893bae652031L, "BedType", "r:c1ca0d93-0221-4e5d-94f3-6bf04aa3666a(HotelBooking.structure)/2805330507320336433", PrimitiveTypeId.INTEGER);
  }

  private final EnumerationDescriptor.MemberDescriptor VALUE_1_0 = new EnumerationDescriptor.MemberDescriptor("1", "Single", "r:c1ca0d93-0221-4e5d-94f3-6bf04aa3666a(HotelBooking.structure)/2805330507320336434", "Single");
  private final EnumerationDescriptor.MemberDescriptor VALUE_2_0 = new EnumerationDescriptor.MemberDescriptor("2", "Double", "r:c1ca0d93-0221-4e5d-94f3-6bf04aa3666a(HotelBooking.structure)/2805330507320336435", "Double");

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return VALUE_1_0;
  }

  @NotNull
  @Override
  public Collection<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return Arrays.asList(VALUE_1_0, VALUE_2_0);
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String string) {
    if (string == null) {
      return null;
    }
    switch (string) {
      case "1":
        return VALUE_1_0;
      case "2":
        return VALUE_2_0;
    }
    return null;
  }
}
