package HotelBooking.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Bed = 0;
  public static final int Booking = 1;
  public static final int BookingManager = 2;
  public static final int Chargeable = 3;
  public static final int Date = 4;
  public static final int Facility = 5;
  public static final int Hotel = 6;
  public static final int Room = 7;
  public static final int StandardRoom = 8;
  public static final int Studio = 9;
  public static final int Suite = 10;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L);
    builder.put(0x2d11723256bb3a7aL, Bed);
    builder.put(0x47b154f6f964356bL, Booking);
    builder.put(0x47b154f6f9643586L, BookingManager);
    builder.put(0x7fad6725e09ca852L, Chargeable);
    builder.put(0x47b154f6f964358bL, Date);
    builder.put(0x7fad6725e0988022L, Facility);
    builder.put(0x2d11723256bb12aeL, Hotel);
    builder.put(0x2d11723256bb3a6bL, Room);
    builder.put(0x2d11723256bb3ce5L, StandardRoom);
    builder.put(0x6c41d16d1d9adfe2L, Studio);
    builder.put(0x7fad6725e0987fdeL, Suite);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
