package HotelBooking.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptBed = createDescriptorForBed();
  /*package*/ final ConceptDescriptor myConceptBooking = createDescriptorForBooking();
  /*package*/ final ConceptDescriptor myConceptBookingManager = createDescriptorForBookingManager();
  /*package*/ final ConceptDescriptor myConceptChargeable = createDescriptorForChargeable();
  /*package*/ final ConceptDescriptor myConceptDate = createDescriptorForDate();
  /*package*/ final ConceptDescriptor myConceptFacility = createDescriptorForFacility();
  /*package*/ final ConceptDescriptor myConceptHotel = createDescriptorForHotel();
  /*package*/ final ConceptDescriptor myConceptRoom = createDescriptorForRoom();
  /*package*/ final ConceptDescriptor myConceptStandardRoom = createDescriptorForStandardRoom();
  /*package*/ final ConceptDescriptor myConceptStudio = createDescriptorForStudio();
  /*package*/ final ConceptDescriptor myConceptSuite = createDescriptorForSuite();
  /*package*/ final EnumerationDescriptor myEnumerationBedType = new EnumerationDescriptor_BedType();
  /*package*/ final EnumerationDescriptor myEnumerationFacillityName = new EnumerationDescriptor_FacillityName();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptBed, myConceptBooking, myConceptBookingManager, myConceptChargeable, myConceptDate, myConceptFacility, myConceptHotel, myConceptRoom, myConceptStandardRoom, myConceptStudio, myConceptSuite);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Bed:
        return myConceptBed;
      case LanguageConceptSwitch.Booking:
        return myConceptBooking;
      case LanguageConceptSwitch.BookingManager:
        return myConceptBookingManager;
      case LanguageConceptSwitch.Chargeable:
        return myConceptChargeable;
      case LanguageConceptSwitch.Date:
        return myConceptDate;
      case LanguageConceptSwitch.Facility:
        return myConceptFacility;
      case LanguageConceptSwitch.Hotel:
        return myConceptHotel;
      case LanguageConceptSwitch.Room:
        return myConceptRoom;
      case LanguageConceptSwitch.StandardRoom:
        return myConceptStandardRoom;
      case LanguageConceptSwitch.Studio:
        return myConceptStudio;
      case LanguageConceptSwitch.Suite:
        return myConceptSuite;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationBedType, myEnumerationFacillityName);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForBed() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HotelBooking", "Bed", 0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x2d11723256bb3a7aL);
    b.class_(false, false, false);
    b.parent(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x7fad6725e09ca852L);
    b.origin("r:c1ca0d93-0221-4e5d-94f3-6bf04aa3666a(HotelBooking.structure)/3247502366839880314");
    b.version(2);
    b.property("type", 0x26ee893bae65202fL).type(MetaIdFactory.dataTypeId(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x26ee893bae652031L)).origin("2805330507320336431").done();
    b.alias("Bed");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForBooking() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HotelBooking", "Booking", 0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x47b154f6f964356bL);
    b.class_(false, false, false);
    b.origin("r:c1ca0d93-0221-4e5d-94f3-6bf04aa3666a(HotelBooking.structure)/5166003667293451627");
    b.version(2);
    b.property("GuestCount", 0x47b154f6f9643579L).type(PrimitiveTypeId.INTEGER).origin("5166003667293451641").done();
    b.property("CustomerName", 0x47b154f6f9643580L).type(PrimitiveTypeId.STRING).origin("5166003667293451648").done();
    b.property("roomNumber", 0x4bf25a0a3dc08386L).type(PrimitiveTypeId.INTEGER).origin("5472535497240773510").done();
    b.aggregate("CheckIn", 0x4bf25a0a3dcc0bf3L).target(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x47b154f6f964358bL).optional(false).ordered(true).multiple(false).origin("5472535497241529331").done();
    b.aggregate("CheckOut", 0x4bf25a0a3dcca052L).target(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x47b154f6f964358bL).optional(false).ordered(true).multiple(false).origin("5472535497241567314").done();
    b.alias("Booking");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForBookingManager() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HotelBooking", "BookingManager", 0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x47b154f6f9643586L);
    b.class_(false, false, false);
    b.origin("r:c1ca0d93-0221-4e5d-94f3-6bf04aa3666a(HotelBooking.structure)/5166003667293451654");
    b.version(2);
    b.aggregate("Bookings", 0x47b154f6f9643587L).target(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x47b154f6f964356bL).optional(true).ordered(true).multiple(true).origin("5166003667293451655").done();
    b.alias("Booking Manager");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForChargeable() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HotelBooking", "Chargeable", 0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x7fad6725e09ca852L);
    b.interface_();
    b.origin("r:c1ca0d93-0221-4e5d-94f3-6bf04aa3666a(HotelBooking.structure)/9200123026167605330");
    b.version(2);
    b.property("price", 0x7fad6725e09ca866L).type(PrimitiveTypeId.INTEGER).origin("9200123026167605350").done();
    b.property("luxury", 0x26ee893bae652025L).type(PrimitiveTypeId.BOOLEAN).origin("2805330507320336421").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDate() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HotelBooking", "Date", 0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x47b154f6f964358bL);
    b.class_(false, false, false);
    b.origin("r:c1ca0d93-0221-4e5d-94f3-6bf04aa3666a(HotelBooking.structure)/5166003667293451659");
    b.version(2);
    b.property("Day", 0x47b154f6f964358cL).type(PrimitiveTypeId.INTEGER).origin("5166003667293451660").done();
    b.property("Month", 0x47b154f6f964358eL).type(PrimitiveTypeId.INTEGER).origin("5166003667293451662").done();
    b.property("Year", 0x47b154f6f9643591L).type(PrimitiveTypeId.INTEGER).origin("5166003667293451665").done();
    b.alias("Date");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFacility() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HotelBooking", "Facility", 0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x7fad6725e0988022L);
    b.class_(false, false, false);
    b.parent(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x7fad6725e09ca852L);
    b.origin("r:c1ca0d93-0221-4e5d-94f3-6bf04aa3666a(HotelBooking.structure)/9200123026167332898");
    b.version(2);
    b.property("type", 0x26ee893bae652778L).type(MetaIdFactory.dataTypeId(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x7fad6725e0a3467dL)).origin("2805330507320338296").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForHotel() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HotelBooking", "Hotel", 0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x2d11723256bb12aeL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:c1ca0d93-0221-4e5d-94f3-6bf04aa3666a(HotelBooking.structure)/3247502366839870126");
    b.version(2);
    b.property("HotelName", 0x2d11723256bb12b7L).type(PrimitiveTypeId.STRING).origin("3247502366839870135").done();
    b.aggregate("Rooms", 0x2d11723256bb3ce3L).target(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x2d11723256bb3a6bL).optional(true).ordered(true).multiple(true).origin("3247502366839880931").done();
    b.aggregate("BookingSystem", 0x47b154f6f964f15eL).target(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x47b154f6f9643586L).optional(false).ordered(true).multiple(false).origin("5166003667293499742").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRoom() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HotelBooking", "Room", 0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x2d11723256bb3a6bL);
    b.class_(false, true, false);
    b.parent(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x7fad6725e09ca852L);
    b.origin("r:c1ca0d93-0221-4e5d-94f3-6bf04aa3666a(HotelBooking.structure)/3247502366839880299");
    b.version(2);
    b.property("roomNumber", 0x2d11723256bb3a78L).type(PrimitiveTypeId.INTEGER).origin("3247502366839880312").done();
    b.property("maxCapacity", 0x26ee893bae64f3a2L).type(PrimitiveTypeId.INTEGER).origin("2805330507320325026").done();
    b.property("maxBeds", 0x3beb13a45ea5ff2L).type(PrimitiveTypeId.INTEGER).origin("269847891528015858").done();
    b.property("maxFacilities", 0x3beb13a45ea5ff6L).type(PrimitiveTypeId.INTEGER).origin("269847891528015862").done();
    b.property("maxLuxuryItems", 0x3beb13a45ea5ffbL).type(PrimitiveTypeId.INTEGER).origin("269847891528015867").done();
    b.aggregate("Facilities", 0x7fad6725e0988025L).target(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x7fad6725e0988022L).optional(false).ordered(true).multiple(true).origin("9200123026167332901").done();
    b.aggregate("Beds", 0x7fad6725e0988016L).target(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x2d11723256bb3a7aL).optional(false).ordered(true).multiple(true).origin("9200123026167332886").done();
    b.alias("Room");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForStandardRoom() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HotelBooking", "StandardRoom", 0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x2d11723256bb3ce5L);
    b.class_(false, false, false);
    b.super_("HotelBooking.structure.Room", 0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x2d11723256bb3a6bL);
    b.origin("r:c1ca0d93-0221-4e5d-94f3-6bf04aa3666a(HotelBooking.structure)/3247502366839880933");
    b.version(2);
    b.alias("StdRoom");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForStudio() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HotelBooking", "Studio", 0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x6c41d16d1d9adfe2L);
    b.class_(false, false, false);
    b.super_("HotelBooking.structure.Room", 0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x2d11723256bb3a6bL);
    b.origin("r:c1ca0d93-0221-4e5d-94f3-6bf04aa3666a(HotelBooking.structure)/7800746296160739298");
    b.version(2);
    b.alias("studio");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSuite() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HotelBooking", "Suite", 0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x7fad6725e0987fdeL);
    b.class_(false, false, false);
    b.super_("HotelBooking.structure.Room", 0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x2d11723256bb3a6bL);
    b.origin("r:c1ca0d93-0221-4e5d-94f3-6bf04aa3666a(HotelBooking.structure)/9200123026167332830");
    b.version(2);
    b.alias("suite");
    return b.create();
  }
}
