package HotelBooking.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import java.util.Map;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.runtime.PropertyConstraintsDescriptor;
import java.util.HashMap;
import jetbrains.mps.smodel.runtime.base.BasePropertyConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.references.BLOperations;
import HotelBooking.behavior.Room__BehaviorDescriptor;

public class Chargeable_Constraints extends BaseConstraintsDescriptor {
  public Chargeable_Constraints() {
    super(MetaAdapterFactory.getInterfaceConcept(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x7fad6725e09ca852L, "HotelBooking.structure.Chargeable"));
  }

  @Override
  protected Map<SProperty, PropertyConstraintsDescriptor> getSpecifiedProperties() {
    Map<SProperty, PropertyConstraintsDescriptor> properties = new HashMap<SProperty, PropertyConstraintsDescriptor>();
    properties.put(MetaAdapterFactory.getProperty(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x7fad6725e09ca852L, 0x7fad6725e09ca866L, "price"), new BasePropertyConstraintsDescriptor(MetaIdFactory.propId(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x7fad6725e09ca852L, 0x7fad6725e09ca866L), this) {
      @Override
      public boolean hasOwnGetter() {
        return true;
      }
      @Override
      public Object getValue(SNode node) {
        String propertyName = "price";
        return SPropertyOperations.getInteger(node, MetaAdapterFactory.getProperty(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x7fad6725e09ca852L, 0x7fad6725e09ca866L, "price"));
      }
      @Override
      public boolean hasOwnSetter() {
        return true;
      }
      @Override
      public void setValue(SNode node, String propertyValue) {
        String propertyName = "price";
        SPropertyOperations.assign(node, MetaAdapterFactory.getProperty(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x7fad6725e09ca852L, 0x7fad6725e09ca866L, "price"), (SPropertyOperations.getInteger(propertyValue)));
        if (SNodeOperations.isInstanceOf(node, MetaAdapterFactory.getConcept(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x2d11723256bb3a6bL, "HotelBooking.structure.Room"))) {
          for (SNode child : SNodeOperations.getChildren(node)) {
            BLOperations.plusAssign(SPropertyOperations.intPropRef(SNodeOperations.cast(node, MetaAdapterFactory.getInterfaceConcept(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x7fad6725e09ca852L, "HotelBooking.structure.Chargeable")), MetaAdapterFactory.getProperty(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x7fad6725e09ca852L, 0x7fad6725e09ca866L, "price")), SPropertyOperations.getInteger(SNodeOperations.cast(child, MetaAdapterFactory.getInterfaceConcept(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x7fad6725e09ca852L, "HotelBooking.structure.Chargeable")), MetaAdapterFactory.getProperty(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x7fad6725e09ca852L, 0x7fad6725e09ca866L, "price")));
          }
        }
      }
      @Override
      public boolean hasOwnValidator() {
        return true;
      }
      @Override
      public boolean validateValue(SNode node, String propertyValue) {
        String propertyName = "price";
        if (SNodeOperations.isInstanceOf(node, MetaAdapterFactory.getConcept(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x2d11723256bb3a6bL, "HotelBooking.structure.Room"))) {
          return true;
        }
        if (SPropertyOperations.getBoolean(node, MetaAdapterFactory.getProperty(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x7fad6725e09ca852L, 0x26ee893bae652025L, "luxury"))) {
          SPropertyOperations.assign(node, MetaAdapterFactory.getProperty(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x7fad6725e09ca852L, 0x7fad6725e09ca866L, "price"), 20);
        }
        if (!(SPropertyOperations.getBoolean(node, MetaAdapterFactory.getProperty(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x7fad6725e09ca852L, 0x26ee893bae652025L, "luxury")))) {
          SPropertyOperations.assign(node, MetaAdapterFactory.getProperty(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x7fad6725e09ca852L, 0x7fad6725e09ca866L, "price"), 0);
        }
        return true;
      }
    });
    properties.put(MetaAdapterFactory.getProperty(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x7fad6725e09ca852L, 0x26ee893bae652025L, "luxury"), new BasePropertyConstraintsDescriptor(MetaIdFactory.propId(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x7fad6725e09ca852L, 0x26ee893bae652025L), this) {
      @Override
      public boolean hasOwnSetter() {
        return true;
      }
      @Override
      public void setValue(SNode node, String propertyValue) {
        String propertyName = "luxury";
        SPropertyOperations.assign(node, MetaAdapterFactory.getProperty(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x7fad6725e09ca852L, 0x26ee893bae652025L, "luxury"), (SPropertyOperations.getBoolean(propertyValue)));
        if (SNodeOperations.isInstanceOf(SNodeOperations.getParent(node), MetaAdapterFactory.getConcept(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x2d11723256bb3a6bL, "HotelBooking.structure.Room")) && !((boolean) Room__BehaviorDescriptor.constraints_id5HgWCcgkX31.invoke(SNodeOperations.cast(SNodeOperations.getParent(node), MetaAdapterFactory.getConcept(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x2d11723256bb3a6bL, "HotelBooking.structure.Room")), SNodeOperations.getParent(node)))) {
          SPropertyOperations.assign(node, MetaAdapterFactory.getProperty(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x7fad6725e09ca852L, 0x26ee893bae652025L, "luxury"), false);
        }
      }
      @Override
      public boolean hasOwnValidator() {
        return true;
      }
      @Override
      public boolean validateValue(SNode node, String propertyValue) {
        String propertyName = "luxury";
        if (SNodeOperations.isInstanceOf(node, MetaAdapterFactory.getConcept(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x2d11723256bb3a6bL, "HotelBooking.structure.Room"))) {
          return (boolean) Room__BehaviorDescriptor.constraints_id5HgWCcgkX31.invoke(SNodeOperations.cast(node, MetaAdapterFactory.getConcept(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x2d11723256bb3a6bL, "HotelBooking.structure.Room")), node);
        }
        return true;
      }
    });
    return properties;
  }
}
