package HotelBooking.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Facility_Constraints extends BaseConstraintsDescriptor {
  public Facility_Constraints() {
    super(MetaAdapterFactory.getConcept(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x7fad6725e0988022L, "HotelBooking.structure.Facility"));
  }

}
