package HotelBooking.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Studio_Constraints extends BaseConstraintsDescriptor {
  public Studio_Constraints() {
    super(MetaAdapterFactory.getConcept(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x6c41d16d1d9adfe2L, "HotelBooking.structure.Studio"));
  }

}
