package HotelBooking.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBehaviorAspectDescriptor;
import jetbrains.mps.core.aspects.behaviour.api.BHDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public final class BehaviorAspectDescriptor extends BaseBehaviorAspectDescriptor {
  private final BHDescriptor myHotel__BehaviorDescriptor = new Hotel__BehaviorDescriptor();
  private final BHDescriptor myRoom__BehaviorDescriptor = new Room__BehaviorDescriptor();
  private final BHDescriptor myBed__BehaviorDescriptor = new Bed__BehaviorDescriptor();
  private final BHDescriptor myStandardRoom__BehaviorDescriptor = new StandardRoom__BehaviorDescriptor();
  private final BHDescriptor myBooking__BehaviorDescriptor = new Booking__BehaviorDescriptor();
  private final BHDescriptor myBookingManager__BehaviorDescriptor = new BookingManager__BehaviorDescriptor();
  private final BHDescriptor myDate__BehaviorDescriptor = new Date__BehaviorDescriptor();
  private final BHDescriptor myStudio__BehaviorDescriptor = new Studio__BehaviorDescriptor();
  private final BHDescriptor mySuite__BehaviorDescriptor = new Suite__BehaviorDescriptor();
  private final BHDescriptor myChargeable__BehaviorDescriptor = new Chargeable__BehaviorDescriptor();

  public BehaviorAspectDescriptor() {
  }

  @Nullable
  public BHDescriptor getDescriptor(@NotNull SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return myBed__BehaviorDescriptor;
      case 1:
        return myBooking__BehaviorDescriptor;
      case 2:
        return myBookingManager__BehaviorDescriptor;
      case 3:
        return myChargeable__BehaviorDescriptor;
      case 4:
        return myDate__BehaviorDescriptor;
      case 5:
        return myHotel__BehaviorDescriptor;
      case 6:
        return myRoom__BehaviorDescriptor;
      case 7:
        return myStandardRoom__BehaviorDescriptor;
      case 8:
        return myStudio__BehaviorDescriptor;
      case 9:
        return mySuite__BehaviorDescriptor;
      default:
    }
    return null;
  }
  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x2d11723256bb3a7aL), MetaIdFactory.conceptId(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x47b154f6f964356bL), MetaIdFactory.conceptId(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x47b154f6f9643586L), MetaIdFactory.conceptId(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x7fad6725e09ca852L), MetaIdFactory.conceptId(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x47b154f6f964358bL), MetaIdFactory.conceptId(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x2d11723256bb12aeL), MetaIdFactory.conceptId(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x2d11723256bb3a6bL), MetaIdFactory.conceptId(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x2d11723256bb3ce5L), MetaIdFactory.conceptId(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x6c41d16d1d9adfe2L), MetaIdFactory.conceptId(0x7f67387345c45fbL, 0xbd3e45c50d906ea1L, 0x7fad6725e0987fdeL)).seal();
}
